on: push
name: 🚀 Deploy App
jobs:
  web-deploy:

    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Run JAR
      run: |
        nohup java -jar target/infom-0.0.1.jar &

    - name: 📂 Sync files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "."
        target: "/var/www/html/api/"